// Code generated by hertz generator.

package user

import (
	"StreamCore/biz/repo"
	"StreamCore/biz/service"
	"StreamCore/pkg/ctl"
	"context"

	user "StreamCore/biz/model/user"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

var serv = service.NewUserService(repo.NewUserRepo())

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var req user.RegisterReq
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, ctl.ResponseError(err, consts.StatusBadRequest))
		return
	}

	if err := serv.Register(ctx, &req); err != nil {
		c.JSON(consts.StatusInternalServerError, ctl.ResponseError(err))
		return
	}

	resp := new(user.RegisterResp)
	resp.Base = ctl.ResponseSuccess()

	c.JSON(consts.StatusOK, resp)
}

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.LoginResp)

	c.JSON(consts.StatusOK, resp)
}

// GetInfo .
// @router /user/info [GET]
func GetInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.InfoQuery
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.InfoResp)

	c.JSON(consts.StatusOK, resp)
}

// UploadAvatar .
// @router /user/avatar/upload [PUT]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.AvatarReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.AvatarResp)

	c.JSON(consts.StatusOK, resp)
}
