// Code generated by hertz generator.

package user

import (
	"StreamCore/biz/service"
	"StreamCore/pkg/ctl"
	"context"

	user "StreamCore/biz/model/user"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

type UserController struct {
	serv *service.UserService
}

func NewUserController(serv *service.UserService) *UserController {
	return &UserController{
		serv: serv,
	}
}

// Register .
// @router /user/register [POST]
func (uc *UserController) Register(ctx context.Context, c *app.RequestContext) {
	var req user.RegisterReq
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, ctl.ResponseError(err, consts.StatusBadRequest))
		return
	}

	if err := uc.serv.Register(ctx, &req); err != nil {
		c.JSON(consts.StatusInternalServerError, ctl.ResponseError(err))
		return
	}

	resp := &user.RegisterResp{
		Base: ctl.ResponseSuccess(),
	}
	c.JSON(consts.StatusOK, resp)
}

// Login .
// @router /user/login [POST]
func (uc *UserController) Login(ctx context.Context, c *app.RequestContext) {
	var req user.LoginReq
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, ctl.ResponseError(err, consts.StatusBadRequest))
		return
	}

	data, auth, err := uc.serv.Login(ctx, &req)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, ctl.ResponseError(err))
		return
	}

	resp := &user.LoginResp{
		Base: ctl.ResponseSuccess(),
		Data: data,
		Auth: auth,
	}
	c.JSON(consts.StatusOK, resp)
}

// GetInfo .
// @router /user/info [GET]
func (uc *UserController) GetInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.InfoQuery
	if err = c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, ctl.ResponseError(err, consts.StatusBadRequest))
		return
	}

	data, err := uc.serv.GetInfo(ctx, &req)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, ctl.ResponseError(err))
		return
	}

	resp := &user.InfoResp{
		Base: ctl.ResponseSuccess(),
		Data: data,
	}
	c.JSON(consts.StatusOK, resp)
}

// UploadAvatar .
// @router /user/avatar/upload [PUT]
func (uc *UserController) UploadAvatar(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.AvatarReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.AvatarResp)

	c.JSON(consts.StatusOK, resp)
}

func contextWithUid(ctx context.Context, c *app.RequestContext) context.Context {
	obj, _ := c.Get("uid")
	uid, _ := obj.(uint)
	return context.WithValue(ctx, "uid", uid)
}
