# https://golangci-lint.run/docs/configuration/file/

version: "2"

run:
  timeout: 5m
  concurrency: 4
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy

formatters:
  enable:
    - gci
    - gofmt
    - goimports
    - gofumpt
    - golines
    - swaggo
  exclusions:
    generated: lax
    warn-unused: true