// Code generated by hertz generator.

package like

import (
	"context"

	like "StreamCore/biz/model/like"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Like .
// @router /like/action [POST]
func Like(ctx context.Context, c *app.RequestContext) {
	var err error
	var req like.ActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(like.ActionResp)

	c.JSON(consts.StatusOK, resp)
}

// ListLike .
// @router /like/list [GET]
func ListLike(ctx context.Context, c *app.RequestContext) {
	var err error
	var req like.ListQuery
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(like.ListResp)

	c.JSON(consts.StatusOK, resp)
}
