// Code generated by hertz generator.

package api

import (
	"context"
	"errors"

	chat "StreamCore/api/model/chat"
	"StreamCore/api/pack"
	"StreamCore/api/rpc"
	kitexchat "StreamCore/kitex_gen/chat"
	"github.com/cloudwego/hertz/pkg/app"
)

// ListWhisperMessagesAll .
// @router /chat/whisper/history/all [GET]
func ListWhisperMessagesAll(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.ListWhisperMessagesAllQuery
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespParamError(c, err)
		return
	}

	resp, err := rpc.ListWhisperMessagesAllRPC(ctx, &kitexchat.ListWhisperMessagesAllQuery{
		PeerUid: req.PeerUID,
	})
	if err != nil {
		pack.RespRPCError(c, err)
		return
	}

	if !pack.RespBizError(c, resp.Base) {
		pack.RespWithData(c, resp.Data)
	}
}

// ListWhisperMessages .
// @router /chat/whisper/history/page [GET]
func ListWhisperMessages(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.ListWhisperMessagesQuery
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespParamError(c, err)
		return
	}
	if req.PageSize != nil && *req.PageSize <= 0 {
		pack.RespParamError(c, errors.New("page_size must be positive int"))
		return
	}
	if req.CursorMsgID != nil && *req.CursorMsgID < 0 {
		pack.RespParamError(c, errors.New("cursor_msg_id must be non-negative int64"))
		return
	}

	resp, err := rpc.ListWhisperMessagesRPC(ctx, &kitexchat.ListWhisperMessagesQuery{
		PeerUid:     req.PeerUID,
		PageSize:    req.PageSize,
		CursorMsgId: req.CursorMsgID,
	})
	if err != nil {
		pack.RespRPCError(c, err)
		return
	}

	if !pack.RespBizError(c, resp.Base) {
		pack.RespWithData(c, resp.Data)
	}
}

// ListGroupMessagesAll .
// @router /chat/group/history/all [GET]
func ListGroupMessagesAll(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.ListGroupMessagesAllQuery
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespParamError(c, err)
		return
	}

	resp, err := rpc.ListGroupMessagesAllRPC(ctx, &kitexchat.ListGroupMessagesAllQuery{
		GroupId: req.GroupID,
	})
	if err != nil {
		pack.RespRPCError(c, err)
		return
	}

	if !pack.RespBizError(c, resp.Base) {
		pack.RespWithData(c, resp.Data)
	}
}

// ListGroupMessages .
// @router /chat/group/history/page [GET]
func ListGroupMessages(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.ListGroupMessagesQuery
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespParamError(c, err)
		return
	}
	if req.PageSize != nil && *req.PageSize <= 0 {
		pack.RespParamError(c, errors.New("page_size must be positive int"))
		return
	}
	if req.CursorMsgID != nil && *req.CursorMsgID < 0 {
		pack.RespParamError(c, errors.New("cursor_msg_id must be non-negative int64"))
		return
	}

	resp, err := rpc.ListGroupMessagesRPC(ctx, &kitexchat.ListGroupMessagesQuery{
		GroupId:     req.GroupID,
		PageSize:    req.PageSize,
		CursorMsgId: req.CursorMsgID,
	})
	if err != nil {
		pack.RespRPCError(c, err)
		return
	}

	if !pack.RespBizError(c, resp.Base) {
		pack.RespWithData(c, resp.Data)
	}
}
