// Code generated by hertz generator.

package api

import (
	"context"

	api "StreamCore/api/model/social"
	"StreamCore/api/pack"
	"StreamCore/api/rpc"
	"StreamCore/kitex_gen/social"
	"github.com/cloudwego/hertz/pkg/app"
)

// Follow .
// @router /relation/action [POST]
func Follow(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FollowReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespParamError(c, err)
		return
	}

	resp, err := rpc.FollowRPC(ctx, &social.FollowReq{
		ToUserId:   req.ToUserID,
		ActionType: req.ActionType,
	})
	if err != nil {
		pack.RespRPCError(c, err)
		return
	}

	if !pack.RespBizError(c, resp.Base) {
		pack.RespSuccess(c)
	}
}

// ListFollows .
// @router /following/list [GET]
func ListFollows(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ListFollowsQuery
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespParamError(c, err)
		return
	}

	resp, err := rpc.ListFollowsRPC(ctx, &social.ListFollowsQuery{
		UserId:   req.UserID,
		PageSize: req.PageSize,
		PageNum:  req.PageNum,
	})
	if err != nil {
		pack.RespRPCError(c, err)
		return
	}

	if !pack.RespBizError(c, resp.Base) {
		pack.RespWithData(c, resp.Data)
	}
}

// ListFollowers .
// @router /follower/list [GET]
func ListFollowers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ListFollowersQuery
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespParamError(c, err)
		return
	}

	resp, err := rpc.ListFollowersRPC(ctx, &social.ListFollowersQuery{
		UserId:   req.UserID,
		PageSize: req.PageSize,
		PageNum:  req.PageNum,
	})
	if err != nil {
		pack.RespRPCError(c, err)
		return
	}

	if !pack.RespBizError(c, resp.Base) {
		pack.RespWithData(c, resp.Data)
	}
}

// ListFriends .
// @router /friends/list [GET]
func ListFriends(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ListFriendsQuery
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespParamError(c, err)
		return
	}

	resp, err := rpc.ListFriendsRPC(ctx, &social.ListFriendsQuery{
		PageSize: req.PageSize,
		PageNum:  req.PageNum,
	})
	if err != nil {
		pack.RespRPCError(c, err)
		return
	}

	if !pack.RespBizError(c, resp.Base) {
		pack.RespWithData(c, resp.Data)
	}
}
