// Code generated by hertz generator.

package api

import (
	api "StreamCore/api/model/user"
	"StreamCore/api/pack"
	"StreamCore/api/rpc"
	"StreamCore/kitex_gen/user"
	"context"

	"github.com/cloudwego/hertz/pkg/app"
)

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespParamError(c, err)
		return
	}
	resp, err := rpc.RegisterRPC(ctx, &user.RegisterReq{
		Username: req.Username,
		Password: req.Password,
	})
	if err != nil {
		pack.RespRPCError(c, err)
		return
	}

	if !pack.RespBizError(c, resp.Base) {
		pack.RespSuccess(c)
	}
}

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespParamError(c, err)
		return
	}

	resp, err := rpc.LoginRPC(ctx, &user.LoginReq{
		Username: req.Username,
		Password: req.Password,
		Code:     req.Code,
	})
	if err != nil {
		pack.RespRPCError(c, err)
		return
	}

	if !pack.RespBizError(c, resp.Base) {
		pack.RespWithData(c, map[string]any{
			"data": resp.Data,
			"auth": resp.Auth,
		})
	}
}

// GetInfo .
// @router /user/info [GET]
func GetInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.InfoQuery
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespParamError(c, err)
		return
	}

	resp, err := rpc.GetInfoRPC(ctx, &user.InfoQuery{
		UserId: req.UserID,
	})
	if err != nil {
		pack.RespRPCError(c, err)
		return
	}

	if !pack.RespBizError(c, resp.Base) {
		pack.RespWithData(c, resp.Data)
	}
}

// UploadAvatar .
// @router /user/avatar/upload [PUT]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.AvatarReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespParamError(c, err)
		return
	}

	resp, err := rpc.UploadAvatarRPC(ctx, &user.AvatarReq{
		Data: req.Data,
	})
	if err != nil {
		pack.RespRPCError(c, err)
		return
	}

	if !pack.RespBizError(c, resp.Base) {
		pack.RespWithData(c, resp.Data)
	}
}

// MFAQrcode .
// @router /auth/mfa/qrcode [GET]
func MFAQrcode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.MFAQrcodeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespParamError(c, err)
		return
	}

	resp, err := rpc.MFAQrcodeRPC(ctx, &user.MFAQrcodeReq{})
	if err != nil {
		pack.RespRPCError(c, err)
		return
	}

	if !pack.RespBizError(c, resp.Base) {
		pack.RespWithData(c, resp.Data)
	}
}

// MFABind .
// @router /auth/mfa/bind [POST]
func MFABind(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.MFABindReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespParamError(c, err)
		return
	}

	resp, err := rpc.MFABindRPC(ctx, &user.MFABindReq{
		Code:   req.Code,
		Secret: req.Secret,
	})
	if err != nil {
		pack.RespRPCError(c, err)
		return
	}

	if !pack.RespBizError(c, resp.Base) {
		pack.RespSuccess(c)
	}
}
