// Code generated by hertz generator.

package api

import (
	"StreamCore/api/middleware"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _mfaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mfabindMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mfaqrcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _deletecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfollowersMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _followingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfollowsMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _friendsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfriendsMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _likeMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _publishlikeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listlikeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinfoMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _avatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadavatarMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _popularMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _publishMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _searchMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _visitMw() []app.HandlerFunc {
	// your code...
	return nil
}
