// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package interaction

import (
	"StreamCore/kitex_gen/common"
	"context"
	"fmt"
)

type PublishLikeReq struct {
	VideoId    *string `thrift:"video_id,1,optional" frugal:"1,optional,string" json:"video_id,omitempty"`
	CommentId  *string `thrift:"comment_id,2,optional" frugal:"2,optional,string" json:"comment_id,omitempty"`
	ActionType int32   `thrift:"action_type,3,required" frugal:"3,required,i32" json:"action_type"`
}

func NewPublishLikeReq() *PublishLikeReq {
	return &PublishLikeReq{}
}

func (p *PublishLikeReq) InitDefault() {
}

var PublishLikeReq_VideoId_DEFAULT string

func (p *PublishLikeReq) GetVideoId() (v string) {
	if !p.IsSetVideoId() {
		return PublishLikeReq_VideoId_DEFAULT
	}
	return *p.VideoId
}

var PublishLikeReq_CommentId_DEFAULT string

func (p *PublishLikeReq) GetCommentId() (v string) {
	if !p.IsSetCommentId() {
		return PublishLikeReq_CommentId_DEFAULT
	}
	return *p.CommentId
}

func (p *PublishLikeReq) GetActionType() (v int32) {
	return p.ActionType
}
func (p *PublishLikeReq) SetVideoId(val *string) {
	p.VideoId = val
}
func (p *PublishLikeReq) SetCommentId(val *string) {
	p.CommentId = val
}
func (p *PublishLikeReq) SetActionType(val int32) {
	p.ActionType = val
}

func (p *PublishLikeReq) IsSetVideoId() bool {
	return p.VideoId != nil
}

func (p *PublishLikeReq) IsSetCommentId() bool {
	return p.CommentId != nil
}

func (p *PublishLikeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishLikeReq(%+v)", *p)
}

var fieldIDToName_PublishLikeReq = map[int16]string{
	1: "video_id",
	2: "comment_id",
	3: "action_type",
}

type PublishLikeResp struct {
	Base *common.BaseResp `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
}

func NewPublishLikeResp() *PublishLikeResp {
	return &PublishLikeResp{}
}

func (p *PublishLikeResp) InitDefault() {
}

var PublishLikeResp_Base_DEFAULT *common.BaseResp

func (p *PublishLikeResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return PublishLikeResp_Base_DEFAULT
	}
	return p.Base
}
func (p *PublishLikeResp) SetBase(val *common.BaseResp) {
	p.Base = val
}

func (p *PublishLikeResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *PublishLikeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishLikeResp(%+v)", *p)
}

var fieldIDToName_PublishLikeResp = map[int16]string{
	1: "base",
}

type ListLikeQuery struct {
	UserId   string `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
	PageSize int32  `thrift:"page_size,2,required" frugal:"2,required,i32" json:"page_size"`
	PageNum  int32  `thrift:"page_num,3,required" frugal:"3,required,i32" json:"page_num"`
}

func NewListLikeQuery() *ListLikeQuery {
	return &ListLikeQuery{}
}

func (p *ListLikeQuery) InitDefault() {
}

func (p *ListLikeQuery) GetUserId() (v string) {
	return p.UserId
}

func (p *ListLikeQuery) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *ListLikeQuery) GetPageNum() (v int32) {
	return p.PageNum
}
func (p *ListLikeQuery) SetUserId(val string) {
	p.UserId = val
}
func (p *ListLikeQuery) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *ListLikeQuery) SetPageNum(val int32) {
	p.PageNum = val
}

func (p *ListLikeQuery) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListLikeQuery(%+v)", *p)
}

var fieldIDToName_ListLikeQuery = map[int16]string{
	1: "user_id",
	2: "page_size",
	3: "page_num",
}

type ListLikeRespData struct {
	Items []*common.VideoInfo `thrift:"items,1,required" frugal:"1,required,list<common.VideoInfo>" json:"items"`
}

func NewListLikeRespData() *ListLikeRespData {
	return &ListLikeRespData{}
}

func (p *ListLikeRespData) InitDefault() {
}

func (p *ListLikeRespData) GetItems() (v []*common.VideoInfo) {
	return p.Items
}
func (p *ListLikeRespData) SetItems(val []*common.VideoInfo) {
	p.Items = val
}

func (p *ListLikeRespData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListLikeRespData(%+v)", *p)
}

var fieldIDToName_ListLikeRespData = map[int16]string{
	1: "items",
}

type ListLikeResp struct {
	Base *common.BaseResp  `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
	Data *ListLikeRespData `thrift:"data,2,required" frugal:"2,required,ListLikeRespData" json:"data"`
}

func NewListLikeResp() *ListLikeResp {
	return &ListLikeResp{}
}

func (p *ListLikeResp) InitDefault() {
}

var ListLikeResp_Base_DEFAULT *common.BaseResp

func (p *ListLikeResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return ListLikeResp_Base_DEFAULT
	}
	return p.Base
}

var ListLikeResp_Data_DEFAULT *ListLikeRespData

func (p *ListLikeResp) GetData() (v *ListLikeRespData) {
	if !p.IsSetData() {
		return ListLikeResp_Data_DEFAULT
	}
	return p.Data
}
func (p *ListLikeResp) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *ListLikeResp) SetData(val *ListLikeRespData) {
	p.Data = val
}

func (p *ListLikeResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListLikeResp) IsSetData() bool {
	return p.Data != nil
}

func (p *ListLikeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListLikeResp(%+v)", *p)
}

var fieldIDToName_ListLikeResp = map[int16]string{
	1: "base",
	2: "data",
}

type PublishCommentReq struct {
	VideoId   *string `thrift:"video_id,1,optional" frugal:"1,optional,string" json:"video_id,omitempty"`
	CommentId *string `thrift:"comment_id,2,optional" frugal:"2,optional,string" json:"comment_id,omitempty"`
	Content   string  `thrift:"content,3,required" frugal:"3,required,string" json:"content"`
}

func NewPublishCommentReq() *PublishCommentReq {
	return &PublishCommentReq{}
}

func (p *PublishCommentReq) InitDefault() {
}

var PublishCommentReq_VideoId_DEFAULT string

func (p *PublishCommentReq) GetVideoId() (v string) {
	if !p.IsSetVideoId() {
		return PublishCommentReq_VideoId_DEFAULT
	}
	return *p.VideoId
}

var PublishCommentReq_CommentId_DEFAULT string

func (p *PublishCommentReq) GetCommentId() (v string) {
	if !p.IsSetCommentId() {
		return PublishCommentReq_CommentId_DEFAULT
	}
	return *p.CommentId
}

func (p *PublishCommentReq) GetContent() (v string) {
	return p.Content
}
func (p *PublishCommentReq) SetVideoId(val *string) {
	p.VideoId = val
}
func (p *PublishCommentReq) SetCommentId(val *string) {
	p.CommentId = val
}
func (p *PublishCommentReq) SetContent(val string) {
	p.Content = val
}

func (p *PublishCommentReq) IsSetVideoId() bool {
	return p.VideoId != nil
}

func (p *PublishCommentReq) IsSetCommentId() bool {
	return p.CommentId != nil
}

func (p *PublishCommentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishCommentReq(%+v)", *p)
}

var fieldIDToName_PublishCommentReq = map[int16]string{
	1: "video_id",
	2: "comment_id",
	3: "content",
}

type PublishCommentResp struct {
	Base *common.BaseResp `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
}

func NewPublishCommentResp() *PublishCommentResp {
	return &PublishCommentResp{}
}

func (p *PublishCommentResp) InitDefault() {
}

var PublishCommentResp_Base_DEFAULT *common.BaseResp

func (p *PublishCommentResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return PublishCommentResp_Base_DEFAULT
	}
	return p.Base
}
func (p *PublishCommentResp) SetBase(val *common.BaseResp) {
	p.Base = val
}

func (p *PublishCommentResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *PublishCommentResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishCommentResp(%+v)", *p)
}

var fieldIDToName_PublishCommentResp = map[int16]string{
	1: "base",
}

type ListCommentQuery struct {
	VideoId   *string `thrift:"video_id,1,optional" frugal:"1,optional,string" json:"video_id,omitempty"`
	CommentId *string `thrift:"comment_id,2,optional" frugal:"2,optional,string" json:"comment_id,omitempty"`
	PageSize  int32   `thrift:"page_size,3,required" frugal:"3,required,i32" json:"page_size"`
	PageNum   int32   `thrift:"page_num,4,required" frugal:"4,required,i32" json:"page_num"`
}

func NewListCommentQuery() *ListCommentQuery {
	return &ListCommentQuery{}
}

func (p *ListCommentQuery) InitDefault() {
}

var ListCommentQuery_VideoId_DEFAULT string

func (p *ListCommentQuery) GetVideoId() (v string) {
	if !p.IsSetVideoId() {
		return ListCommentQuery_VideoId_DEFAULT
	}
	return *p.VideoId
}

var ListCommentQuery_CommentId_DEFAULT string

func (p *ListCommentQuery) GetCommentId() (v string) {
	if !p.IsSetCommentId() {
		return ListCommentQuery_CommentId_DEFAULT
	}
	return *p.CommentId
}

func (p *ListCommentQuery) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *ListCommentQuery) GetPageNum() (v int32) {
	return p.PageNum
}
func (p *ListCommentQuery) SetVideoId(val *string) {
	p.VideoId = val
}
func (p *ListCommentQuery) SetCommentId(val *string) {
	p.CommentId = val
}
func (p *ListCommentQuery) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *ListCommentQuery) SetPageNum(val int32) {
	p.PageNum = val
}

func (p *ListCommentQuery) IsSetVideoId() bool {
	return p.VideoId != nil
}

func (p *ListCommentQuery) IsSetCommentId() bool {
	return p.CommentId != nil
}

func (p *ListCommentQuery) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListCommentQuery(%+v)", *p)
}

var fieldIDToName_ListCommentQuery = map[int16]string{
	1: "video_id",
	2: "comment_id",
	3: "page_size",
	4: "page_num",
}

type ListCommentRespData struct {
	Items []*common.CommentInfo `thrift:"items,1,required" frugal:"1,required,list<common.CommentInfo>" json:"items"`
}

func NewListCommentRespData() *ListCommentRespData {
	return &ListCommentRespData{}
}

func (p *ListCommentRespData) InitDefault() {
}

func (p *ListCommentRespData) GetItems() (v []*common.CommentInfo) {
	return p.Items
}
func (p *ListCommentRespData) SetItems(val []*common.CommentInfo) {
	p.Items = val
}

func (p *ListCommentRespData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListCommentRespData(%+v)", *p)
}

var fieldIDToName_ListCommentRespData = map[int16]string{
	1: "items",
}

type ListCommentResp struct {
	Base *common.BaseResp     `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
	Data *ListCommentRespData `thrift:"data,2,required" frugal:"2,required,ListCommentRespData" json:"data"`
}

func NewListCommentResp() *ListCommentResp {
	return &ListCommentResp{}
}

func (p *ListCommentResp) InitDefault() {
}

var ListCommentResp_Base_DEFAULT *common.BaseResp

func (p *ListCommentResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return ListCommentResp_Base_DEFAULT
	}
	return p.Base
}

var ListCommentResp_Data_DEFAULT *ListCommentRespData

func (p *ListCommentResp) GetData() (v *ListCommentRespData) {
	if !p.IsSetData() {
		return ListCommentResp_Data_DEFAULT
	}
	return p.Data
}
func (p *ListCommentResp) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *ListCommentResp) SetData(val *ListCommentRespData) {
	p.Data = val
}

func (p *ListCommentResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListCommentResp) IsSetData() bool {
	return p.Data != nil
}

func (p *ListCommentResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListCommentResp(%+v)", *p)
}

var fieldIDToName_ListCommentResp = map[int16]string{
	1: "base",
	2: "data",
}

type DeleteCommentReq struct {
	VideoId   string `thrift:"video_id,1,required" frugal:"1,required,string" json:"video_id"`
	CommentId string `thrift:"comment_id,2,required" frugal:"2,required,string" json:"comment_id"`
}

func NewDeleteCommentReq() *DeleteCommentReq {
	return &DeleteCommentReq{}
}

func (p *DeleteCommentReq) InitDefault() {
}

func (p *DeleteCommentReq) GetVideoId() (v string) {
	return p.VideoId
}

func (p *DeleteCommentReq) GetCommentId() (v string) {
	return p.CommentId
}
func (p *DeleteCommentReq) SetVideoId(val string) {
	p.VideoId = val
}
func (p *DeleteCommentReq) SetCommentId(val string) {
	p.CommentId = val
}

func (p *DeleteCommentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteCommentReq(%+v)", *p)
}

var fieldIDToName_DeleteCommentReq = map[int16]string{
	1: "video_id",
	2: "comment_id",
}

type DeleteCommentResp struct {
	Base *common.BaseResp `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
}

func NewDeleteCommentResp() *DeleteCommentResp {
	return &DeleteCommentResp{}
}

func (p *DeleteCommentResp) InitDefault() {
}

var DeleteCommentResp_Base_DEFAULT *common.BaseResp

func (p *DeleteCommentResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return DeleteCommentResp_Base_DEFAULT
	}
	return p.Base
}
func (p *DeleteCommentResp) SetBase(val *common.BaseResp) {
	p.Base = val
}

func (p *DeleteCommentResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeleteCommentResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteCommentResp(%+v)", *p)
}

var fieldIDToName_DeleteCommentResp = map[int16]string{
	1: "base",
}

type InteractionService interface {
	PublishLike(ctx context.Context, req *PublishLikeReq) (r *PublishLikeResp, err error)

	ListLike(ctx context.Context, req *ListLikeQuery) (r *ListLikeResp, err error)

	PublishComment(ctx context.Context, req *PublishCommentReq) (r *PublishCommentResp, err error)

	ListComment(ctx context.Context, query *ListCommentQuery) (r *ListCommentResp, err error)

	DeleteComment(ctx context.Context, req *DeleteCommentReq) (r *DeleteCommentResp, err error)
}

type InteractionServicePublishLikeArgs struct {
	Req *PublishLikeReq `thrift:"req,1,required" frugal:"1,required,PublishLikeReq" json:"req"`
}

func NewInteractionServicePublishLikeArgs() *InteractionServicePublishLikeArgs {
	return &InteractionServicePublishLikeArgs{}
}

func (p *InteractionServicePublishLikeArgs) InitDefault() {
}

var InteractionServicePublishLikeArgs_Req_DEFAULT *PublishLikeReq

func (p *InteractionServicePublishLikeArgs) GetReq() (v *PublishLikeReq) {
	if !p.IsSetReq() {
		return InteractionServicePublishLikeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InteractionServicePublishLikeArgs) SetReq(val *PublishLikeReq) {
	p.Req = val
}

func (p *InteractionServicePublishLikeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InteractionServicePublishLikeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InteractionServicePublishLikeArgs(%+v)", *p)
}

var fieldIDToName_InteractionServicePublishLikeArgs = map[int16]string{
	1: "req",
}

type InteractionServicePublishLikeResult struct {
	Success *PublishLikeResp `thrift:"success,0,optional" frugal:"0,optional,PublishLikeResp" json:"success,omitempty"`
}

func NewInteractionServicePublishLikeResult() *InteractionServicePublishLikeResult {
	return &InteractionServicePublishLikeResult{}
}

func (p *InteractionServicePublishLikeResult) InitDefault() {
}

var InteractionServicePublishLikeResult_Success_DEFAULT *PublishLikeResp

func (p *InteractionServicePublishLikeResult) GetSuccess() (v *PublishLikeResp) {
	if !p.IsSetSuccess() {
		return InteractionServicePublishLikeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InteractionServicePublishLikeResult) SetSuccess(x interface{}) {
	p.Success = x.(*PublishLikeResp)
}

func (p *InteractionServicePublishLikeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InteractionServicePublishLikeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InteractionServicePublishLikeResult(%+v)", *p)
}

var fieldIDToName_InteractionServicePublishLikeResult = map[int16]string{
	0: "success",
}

type InteractionServiceListLikeArgs struct {
	Req *ListLikeQuery `thrift:"req,1,required" frugal:"1,required,ListLikeQuery" json:"req"`
}

func NewInteractionServiceListLikeArgs() *InteractionServiceListLikeArgs {
	return &InteractionServiceListLikeArgs{}
}

func (p *InteractionServiceListLikeArgs) InitDefault() {
}

var InteractionServiceListLikeArgs_Req_DEFAULT *ListLikeQuery

func (p *InteractionServiceListLikeArgs) GetReq() (v *ListLikeQuery) {
	if !p.IsSetReq() {
		return InteractionServiceListLikeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InteractionServiceListLikeArgs) SetReq(val *ListLikeQuery) {
	p.Req = val
}

func (p *InteractionServiceListLikeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InteractionServiceListLikeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InteractionServiceListLikeArgs(%+v)", *p)
}

var fieldIDToName_InteractionServiceListLikeArgs = map[int16]string{
	1: "req",
}

type InteractionServiceListLikeResult struct {
	Success *ListLikeResp `thrift:"success,0,optional" frugal:"0,optional,ListLikeResp" json:"success,omitempty"`
}

func NewInteractionServiceListLikeResult() *InteractionServiceListLikeResult {
	return &InteractionServiceListLikeResult{}
}

func (p *InteractionServiceListLikeResult) InitDefault() {
}

var InteractionServiceListLikeResult_Success_DEFAULT *ListLikeResp

func (p *InteractionServiceListLikeResult) GetSuccess() (v *ListLikeResp) {
	if !p.IsSetSuccess() {
		return InteractionServiceListLikeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InteractionServiceListLikeResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListLikeResp)
}

func (p *InteractionServiceListLikeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InteractionServiceListLikeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InteractionServiceListLikeResult(%+v)", *p)
}

var fieldIDToName_InteractionServiceListLikeResult = map[int16]string{
	0: "success",
}

type InteractionServicePublishCommentArgs struct {
	Req *PublishCommentReq `thrift:"req,1,required" frugal:"1,required,PublishCommentReq" json:"req"`
}

func NewInteractionServicePublishCommentArgs() *InteractionServicePublishCommentArgs {
	return &InteractionServicePublishCommentArgs{}
}

func (p *InteractionServicePublishCommentArgs) InitDefault() {
}

var InteractionServicePublishCommentArgs_Req_DEFAULT *PublishCommentReq

func (p *InteractionServicePublishCommentArgs) GetReq() (v *PublishCommentReq) {
	if !p.IsSetReq() {
		return InteractionServicePublishCommentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InteractionServicePublishCommentArgs) SetReq(val *PublishCommentReq) {
	p.Req = val
}

func (p *InteractionServicePublishCommentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InteractionServicePublishCommentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InteractionServicePublishCommentArgs(%+v)", *p)
}

var fieldIDToName_InteractionServicePublishCommentArgs = map[int16]string{
	1: "req",
}

type InteractionServicePublishCommentResult struct {
	Success *PublishCommentResp `thrift:"success,0,optional" frugal:"0,optional,PublishCommentResp" json:"success,omitempty"`
}

func NewInteractionServicePublishCommentResult() *InteractionServicePublishCommentResult {
	return &InteractionServicePublishCommentResult{}
}

func (p *InteractionServicePublishCommentResult) InitDefault() {
}

var InteractionServicePublishCommentResult_Success_DEFAULT *PublishCommentResp

func (p *InteractionServicePublishCommentResult) GetSuccess() (v *PublishCommentResp) {
	if !p.IsSetSuccess() {
		return InteractionServicePublishCommentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InteractionServicePublishCommentResult) SetSuccess(x interface{}) {
	p.Success = x.(*PublishCommentResp)
}

func (p *InteractionServicePublishCommentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InteractionServicePublishCommentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InteractionServicePublishCommentResult(%+v)", *p)
}

var fieldIDToName_InteractionServicePublishCommentResult = map[int16]string{
	0: "success",
}

type InteractionServiceListCommentArgs struct {
	Query *ListCommentQuery `thrift:"query,1,required" frugal:"1,required,ListCommentQuery" json:"query"`
}

func NewInteractionServiceListCommentArgs() *InteractionServiceListCommentArgs {
	return &InteractionServiceListCommentArgs{}
}

func (p *InteractionServiceListCommentArgs) InitDefault() {
}

var InteractionServiceListCommentArgs_Query_DEFAULT *ListCommentQuery

func (p *InteractionServiceListCommentArgs) GetQuery() (v *ListCommentQuery) {
	if !p.IsSetQuery() {
		return InteractionServiceListCommentArgs_Query_DEFAULT
	}
	return p.Query
}
func (p *InteractionServiceListCommentArgs) SetQuery(val *ListCommentQuery) {
	p.Query = val
}

func (p *InteractionServiceListCommentArgs) IsSetQuery() bool {
	return p.Query != nil
}

func (p *InteractionServiceListCommentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InteractionServiceListCommentArgs(%+v)", *p)
}

var fieldIDToName_InteractionServiceListCommentArgs = map[int16]string{
	1: "query",
}

type InteractionServiceListCommentResult struct {
	Success *ListCommentResp `thrift:"success,0,optional" frugal:"0,optional,ListCommentResp" json:"success,omitempty"`
}

func NewInteractionServiceListCommentResult() *InteractionServiceListCommentResult {
	return &InteractionServiceListCommentResult{}
}

func (p *InteractionServiceListCommentResult) InitDefault() {
}

var InteractionServiceListCommentResult_Success_DEFAULT *ListCommentResp

func (p *InteractionServiceListCommentResult) GetSuccess() (v *ListCommentResp) {
	if !p.IsSetSuccess() {
		return InteractionServiceListCommentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InteractionServiceListCommentResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListCommentResp)
}

func (p *InteractionServiceListCommentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InteractionServiceListCommentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InteractionServiceListCommentResult(%+v)", *p)
}

var fieldIDToName_InteractionServiceListCommentResult = map[int16]string{
	0: "success",
}

type InteractionServiceDeleteCommentArgs struct {
	Req *DeleteCommentReq `thrift:"req,1,required" frugal:"1,required,DeleteCommentReq" json:"req"`
}

func NewInteractionServiceDeleteCommentArgs() *InteractionServiceDeleteCommentArgs {
	return &InteractionServiceDeleteCommentArgs{}
}

func (p *InteractionServiceDeleteCommentArgs) InitDefault() {
}

var InteractionServiceDeleteCommentArgs_Req_DEFAULT *DeleteCommentReq

func (p *InteractionServiceDeleteCommentArgs) GetReq() (v *DeleteCommentReq) {
	if !p.IsSetReq() {
		return InteractionServiceDeleteCommentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InteractionServiceDeleteCommentArgs) SetReq(val *DeleteCommentReq) {
	p.Req = val
}

func (p *InteractionServiceDeleteCommentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InteractionServiceDeleteCommentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InteractionServiceDeleteCommentArgs(%+v)", *p)
}

var fieldIDToName_InteractionServiceDeleteCommentArgs = map[int16]string{
	1: "req",
}

type InteractionServiceDeleteCommentResult struct {
	Success *DeleteCommentResp `thrift:"success,0,optional" frugal:"0,optional,DeleteCommentResp" json:"success,omitempty"`
}

func NewInteractionServiceDeleteCommentResult() *InteractionServiceDeleteCommentResult {
	return &InteractionServiceDeleteCommentResult{}
}

func (p *InteractionServiceDeleteCommentResult) InitDefault() {
}

var InteractionServiceDeleteCommentResult_Success_DEFAULT *DeleteCommentResp

func (p *InteractionServiceDeleteCommentResult) GetSuccess() (v *DeleteCommentResp) {
	if !p.IsSetSuccess() {
		return InteractionServiceDeleteCommentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InteractionServiceDeleteCommentResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteCommentResp)
}

func (p *InteractionServiceDeleteCommentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InteractionServiceDeleteCommentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InteractionServiceDeleteCommentResult(%+v)", *p)
}

var fieldIDToName_InteractionServiceDeleteCommentResult = map[int16]string{
	0: "success",
}
