// Code generated by hertz generator.

package stream

import (
	"StreamCore/biz/middleware"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _popularMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _publishMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _searchMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}
