// Code generated by Kitex v0.15.2. DO NOT EDIT.

package interactionservice

import (
	interaction "StreamCore/kitex_gen/interaction"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PublishLike(ctx context.Context, req *interaction.PublishLikeReq, callOptions ...callopt.Option) (r *interaction.PublishLikeResp, err error)
	ListLike(ctx context.Context, req *interaction.ListLikeQuery, callOptions ...callopt.Option) (r *interaction.ListLikeResp, err error)
	PublishComment(ctx context.Context, req *interaction.PublishCommentReq, callOptions ...callopt.Option) (r *interaction.PublishCommentResp, err error)
	ListComment(ctx context.Context, query *interaction.ListCommentQuery, callOptions ...callopt.Option) (r *interaction.ListCommentResp, err error)
	DeleteComment(ctx context.Context, req *interaction.DeleteCommentReq, callOptions ...callopt.Option) (r *interaction.DeleteCommentResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kInteractionServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInteractionServiceClient struct {
	*kClient
}

func (p *kInteractionServiceClient) PublishLike(ctx context.Context, req *interaction.PublishLikeReq, callOptions ...callopt.Option) (r *interaction.PublishLikeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishLike(ctx, req)
}

func (p *kInteractionServiceClient) ListLike(ctx context.Context, req *interaction.ListLikeQuery, callOptions ...callopt.Option) (r *interaction.ListLikeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListLike(ctx, req)
}

func (p *kInteractionServiceClient) PublishComment(ctx context.Context, req *interaction.PublishCommentReq, callOptions ...callopt.Option) (r *interaction.PublishCommentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishComment(ctx, req)
}

func (p *kInteractionServiceClient) ListComment(ctx context.Context, query *interaction.ListCommentQuery, callOptions ...callopt.Option) (r *interaction.ListCommentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListComment(ctx, query)
}

func (p *kInteractionServiceClient) DeleteComment(ctx context.Context, req *interaction.DeleteCommentReq, callOptions ...callopt.Option) (r *interaction.DeleteCommentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteComment(ctx, req)
}
