// Code generated by Kitex v0.15.2. DO NOT EDIT.

package socialservice

import (
	social "StreamCore/kitex_gen/social"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Follow(ctx context.Context, req *social.FollowReq, callOptions ...callopt.Option) (r *social.FollowResp, err error)
	ListFollows(ctx context.Context, req *social.ListFollowsQuery, callOptions ...callopt.Option) (r *social.ListFollowsResp, err error)
	ListFollowers(ctx context.Context, req *social.ListFollowersQuery, callOptions ...callopt.Option) (r *social.ListFollowersResp, err error)
	ListFriends(ctx context.Context, req *social.ListFriendsQuery, callOptions ...callopt.Option) (r *social.ListFriendsResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kSocialServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSocialServiceClient struct {
	*kClient
}

func (p *kSocialServiceClient) Follow(ctx context.Context, req *social.FollowReq, callOptions ...callopt.Option) (r *social.FollowResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Follow(ctx, req)
}

func (p *kSocialServiceClient) ListFollows(ctx context.Context, req *social.ListFollowsQuery, callOptions ...callopt.Option) (r *social.ListFollowsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFollows(ctx, req)
}

func (p *kSocialServiceClient) ListFollowers(ctx context.Context, req *social.ListFollowersQuery, callOptions ...callopt.Option) (r *social.ListFollowersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFollowers(ctx, req)
}

func (p *kSocialServiceClient) ListFriends(ctx context.Context, req *social.ListFriendsQuery, callOptions ...callopt.Option) (r *social.ListFriendsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFriends(ctx, req)
}
