// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	comment "StreamCore/biz/router/comment"
	like "StreamCore/biz/router/like"
	social "StreamCore/biz/router/social"
	stream "StreamCore/biz/router/stream"
	user "StreamCore/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	social.Register(r)

	comment.Register(r)

	like.Register(r)

	stream.Register(r)

	user.Register(r)
}
