// Code generated by Kitex v0.15.2. DO NOT EDIT.

package groupservice

import (
	group "StreamCore/kitex_gen/group"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateGroup": kitex.NewMethodInfo(
		createGroupHandler,
		newGroupServiceCreateGroupArgs,
		newGroupServiceCreateGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ApplyJoinGroup": kitex.NewMethodInfo(
		applyJoinGroupHandler,
		newGroupServiceApplyJoinGroupArgs,
		newGroupServiceApplyJoinGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"IsGroupMember": kitex.NewMethodInfo(
		isGroupMemberHandler,
		newGroupServiceIsGroupMemberArgs,
		newGroupServiceIsGroupMemberResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListGroupMemberIds": kitex.NewMethodInfo(
		listGroupMemberIdsHandler,
		newGroupServiceListGroupMemberIdsArgs,
		newGroupServiceListGroupMemberIdsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RespondGroupApply": kitex.NewMethodInfo(
		respondGroupApplyHandler,
		newGroupServiceRespondGroupApplyArgs,
		newGroupServiceRespondGroupApplyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	groupServiceServiceInfo                = NewServiceInfo()
	groupServiceServiceInfoForClient       = NewServiceInfoForClient()
	groupServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return groupServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return groupServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return groupServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "GroupService"
	handlerType := (*group.GroupService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "group",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func createGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceCreateGroupArgs)
	realResult := result.(*group.GroupServiceCreateGroupResult)
	success, err := handler.(group.GroupService).CreateGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceCreateGroupArgs() interface{} {
	return group.NewGroupServiceCreateGroupArgs()
}

func newGroupServiceCreateGroupResult() interface{} {
	return group.NewGroupServiceCreateGroupResult()
}

func applyJoinGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceApplyJoinGroupArgs)
	realResult := result.(*group.GroupServiceApplyJoinGroupResult)
	success, err := handler.(group.GroupService).ApplyJoinGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceApplyJoinGroupArgs() interface{} {
	return group.NewGroupServiceApplyJoinGroupArgs()
}

func newGroupServiceApplyJoinGroupResult() interface{} {
	return group.NewGroupServiceApplyJoinGroupResult()
}

func isGroupMemberHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceIsGroupMemberArgs)
	realResult := result.(*group.GroupServiceIsGroupMemberResult)
	success, err := handler.(group.GroupService).IsGroupMember(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceIsGroupMemberArgs() interface{} {
	return group.NewGroupServiceIsGroupMemberArgs()
}

func newGroupServiceIsGroupMemberResult() interface{} {
	return group.NewGroupServiceIsGroupMemberResult()
}

func listGroupMemberIdsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceListGroupMemberIdsArgs)
	realResult := result.(*group.GroupServiceListGroupMemberIdsResult)
	success, err := handler.(group.GroupService).ListGroupMemberIds(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceListGroupMemberIdsArgs() interface{} {
	return group.NewGroupServiceListGroupMemberIdsArgs()
}

func newGroupServiceListGroupMemberIdsResult() interface{} {
	return group.NewGroupServiceListGroupMemberIdsResult()
}

func respondGroupApplyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceRespondGroupApplyArgs)
	realResult := result.(*group.GroupServiceRespondGroupApplyResult)
	success, err := handler.(group.GroupService).RespondGroupApply(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceRespondGroupApplyArgs() interface{} {
	return group.NewGroupServiceRespondGroupApplyArgs()
}

func newGroupServiceRespondGroupApplyResult() interface{} {
	return group.NewGroupServiceRespondGroupApplyResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateGroup(ctx context.Context, req *group.CreateGroupReq) (r *group.CreateGroupResp, err error) {
	var _args group.GroupServiceCreateGroupArgs
	_args.Req = req
	var _result group.GroupServiceCreateGroupResult
	if err = p.c.Call(ctx, "CreateGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ApplyJoinGroup(ctx context.Context, req *group.ApplyJoinGroupReq) (r *group.ApplyJoinGroupResp, err error) {
	var _args group.GroupServiceApplyJoinGroupArgs
	_args.Req = req
	var _result group.GroupServiceApplyJoinGroupResult
	if err = p.c.Call(ctx, "ApplyJoinGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IsGroupMember(ctx context.Context, req *group.IsGroupMemberReq) (r *group.IsGroupMemberResp, err error) {
	var _args group.GroupServiceIsGroupMemberArgs
	_args.Req = req
	var _result group.GroupServiceIsGroupMemberResult
	if err = p.c.Call(ctx, "IsGroupMember", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListGroupMemberIds(ctx context.Context, req *group.ListGroupMemberIdsReq) (r *group.ListGroupMemberIdsResp, err error) {
	var _args group.GroupServiceListGroupMemberIdsArgs
	_args.Req = req
	var _result group.GroupServiceListGroupMemberIdsResult
	if err = p.c.Call(ctx, "ListGroupMemberIds", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RespondGroupApply(ctx context.Context, req *group.RespondGroupApplyReq) (r *group.RespondGroupApplyResp, err error) {
	var _args group.GroupServiceRespondGroupApplyArgs
	_args.Req = req
	var _result group.GroupServiceRespondGroupApplyResult
	if err = p.c.Call(ctx, "RespondGroupApply", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
